### ISSUE TITLE
specific utterance triggers 2 faq actions

### ISSUE THREAD

**Issue by LS1707** [RasaHQ/rasa-demo#228] opened 2018-12-06 14:30 UTC
https://website-demo.rasa.com/conversations/linda/1544106316.0156183

that only happens with "and what are slots?"

**Comment by akelad** [comment] 2018-12-07 16:59
i had your exact conversation and couldn't reproduce this. either it's fixed with the new core model or core was being weird. gonna close

**Closed by akelad** 2018-12-07 16:59 UTC
Labels: bug, faq
